services:
    eventstorm_api:
        container_name: eventstorm_api
        image: ${DOCKER_REGISTRY-}eventstormapi
        build:
            context: .
            dockerfile: src/EventStorm.API/Dockerfile
        env_file: src/EventStorm.API/api.env
        depends_on:
            - eventstorm_db
        networks:
            - eventstorm_network

    eventstorm_db:
        container_name: eventstorm_db
        image: postgres
        env_file: src/EventStorm.API/db.env
        networks:
            - eventstorm_network

networks:
    eventstorm_network:
        driver: bridge